name: ODBC Driver

on:
  pull_request:
  push:

jobs:
  windows-odbc:
    runs-on: windows-latest
    steps:
      - name: Create repo directories
        run: |
          mkdir ../../github

      - name: Clone vcpkg
        run: |
          cd ../../github
          git clone https://github.com/microsoft/vcpkg.git

      - name: Set up vcpkg
        run: |
          cd ../../github
          ./vcpkg/bootstrap-vcpkg.bat
          cd vcpkg
          pwd >> $VCPKG_ROOT

      - name: Clone arrow
        run: |
          cd ../../github
          git clone https://github.com/apache/arrow.git

      - name: Clone flight odbc
        run: |
          cd ../../github
          git clone https://github.com/dbt-labs/flightsql-odbc.git

      - name: Install CMake
        uses: ssrobins/install-cmake@v1

      - uses: actions/checkout@v4

      - name: Change repo path to local repos
        run: |
           (Get-Content .\build_win64.bat).Replace('ARROW_GIT_REPOSITORY="https://github.com/apache/arrow"', 'ARROW_GIT_REPOSITORY="D:/a/github/arrow"') | Set-Content .\build_win64.bat
           (Get-Content .\build_win64.bat).Replace('ODBCABSTRACTION_REPO="../flightsql-odbc"', 'ODBCABSTRACTION_REPO="D:/a/github/flightsql-odbc"') | Set-Content .\build_win64.bat

      - name: Upload bat file
        uses: actions/upload-artifact@v4
        with:
          name: build_win64.bat
          path: '.\build_win64.bat'
