name: ODBC Driver

on:
  pull_request:
  push:

jobs:
  windows-odbc:
    runs-on: windows-latest
    steps:
      - name: Create repo directories
        run: |
          mkdir github
          cd github
    
      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg/
          ./vcpkg/bootstrap-vcpkg.bat
          cd vcpkg
          pwd >> $VCPKG_ROOT
          echo $VCPKG_ROOT

      - name: Clone arrow
        run: |
          cd ..
          pwd
          git clone https://github.com/apache/arrow.git

      - name: Clone flight
        run: |
          git clone https://github.com/dbt-labs/flightsql-odbc.git

      - name: Install CMake
        uses: ssrobins/install-cmake@v1

      - uses: actions/checkout@v4

      - name: Show directory tree
        run: tree
