name: ODBC Driver

on:
  pull_request:
  push:

jobs:
  windows-odbc:
    runs-on: windows-latest
    steps:
      - name: Create repo directories
        run: |
          mkdir github
          cd github

      - name: Clone
        run: |
          cd github
          git clone https://github.com/microsoft/vcpkg.git
          pwd
          tree

      # - name: Clone vcpkg
      #   uses: actions/checkout@v4
      #   with:
      #     repository: microsoft/vcpkg
    
      - name: Set up vcpkg
        run: |
          pwd
          ./vcpkg/bootstrap-vcpkg.bat
          cd vcpkg
          pwd >> $VCPKG_ROOT
          echo $VCPKG_ROOT

      - name: Clone arrow
        uses: actions/checkout@v4
        with:
          repository: arrow/arrow

      - name: Clone flight
        uses: actions/checkout@v4
        with:
          repository: dbt-labs/flightsql-odbc

      - name: Install CMake
        uses: ssrobins/install-cmake@v1

      - uses: actions/checkout@v4

      - name: Show directory tree
        run: |
          echo $VCPKG_ROOT
          tree
